tinyMCE.addI18n('en.spellchecker_dlg',{
title:"Check Spelling",
notindictionary:"Not in dictionary:",
changeto:"Change to:",
suggestions:"Suggestions:",
addwordsto:"Add words to:",
ignore:"<u>I</u>gnore",
ignoreAll:"Ign<u>o</u>re All",
change:"Chan<u>g</u>e",
changeAll:"C<u>h</u>ange All",
add:"<u>A</u>dd",
undo:"<u>U</u>ndo",
cancel:"<u>C</u>ancel",
no_suggestions_found:"(No Suggestions Found)",
ignoreAccessKey:"i",
ignoreAllAccessKey:"o",
changeAccessKey:"g",
changeAllAccessKey:"h",
addAccessKey:"a",
cancelAccessKey:"c",
undoAccessKey:"u"
});